import { Dimensions, StyleSheet } from "react-native";
import { C, S, T } from "../theme";

const SCREEN_W = Dimensions.get("window").width;
const GRID_GAP = S.cardGap;
const CARD_W = (SCREEN_W - S.screenPadding * 2 - GRID_GAP) / 2;

export const auction = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: C.bg,
  },
  root: {
    flex: 1,
  },
  scroll: {
    paddingHorizontal: S.screenPadding,
    paddingTop: 6,
    paddingBottom: S.scrollPaddingBottom,
  },

  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: S.md,
    marginBottom: S.lg,
  },
  searchBar: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: C.elevated,
    borderRadius: S.radiusSmall,
    borderWidth: 1,
    borderColor: C.border,
    paddingHorizontal: S.md,
    gap: S.sm,
    height: 42,
  },
  searchInput: {
    flex: 1,
    color: C.textPrimary,
    fontSize: 14,
    fontWeight: "500",
  },
  iconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: C.elevated,
    borderWidth: 1,
    borderColor: C.borderIcon,
    alignItems: "center",
    justifyContent: "center",
  },

  filterScroll: {
    gap: S.pillGap,
    marginBottom: S.md,
  },
  sortScroll: {
    gap: 8,
    marginBottom: S.xl,
    paddingLeft: 2,
  },
  sortChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: C.elevated,
    borderRadius: S.radiusPill,
    borderWidth: 1,
    borderColor: C.border,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  sortChipActive: {
    backgroundColor: C.accentGlow,
    borderColor: C.accent,
  },
  sortChipText: {
    color: C.textSecondary,
    fontSize: 11,
    fontWeight: "700",
  },
  sortChipTextActive: {
    color: C.textAccent,
  },

  emptyWrap: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
    gap: 12,
  },
  emptyText: {
    color: C.textMuted,
    fontSize: 14,
    fontWeight: "600",
  },

  refreshSkeletonWrap: {
    gap: S.md,
    marginBottom: S.lg,
  },
  refreshSkeletonHeader: {
    height: 42,
    borderRadius: S.radiusSmall,
    backgroundColor: C.elevated,
    borderWidth: 1,
    borderColor: C.border,
  },
  refreshSkeletonPills: {
    height: 32,
    borderRadius: 16,
    backgroundColor: C.elevated,
    borderWidth: 1,
    borderColor: C.border,
    width: "80%",
  },
  refreshSkeletonGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: GRID_GAP,
  },
  refreshSkeletonCard: {
    width: CARD_W,
    height: CARD_W * 1.65,
    borderRadius: S.radiusCard,
    backgroundColor: C.elevated,
    borderWidth: 1,
    borderColor: C.border,
  },

  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: GRID_GAP,
  },

  card: {
    width: CARD_W,
    backgroundColor: C.surface,
    borderRadius: S.radiusCard,
    borderWidth: 1,
    borderColor: C.border,
    padding: S.md,
    overflow: "hidden",
  },
  artArea: {
    width: "100%",
    height: CARD_W * 1.2,
    borderRadius: S.radiusCardInner,
    backgroundColor: C.cardAlt,
    borderWidth: 1,
    borderColor: C.borderCard,
    marginBottom: S.md,
    overflow: "hidden",
  },
  artImage: {
    width: "100%",
    height: "100%",
    borderRadius: S.radiusCardInner,
  },
  timerBadge: {
    position: "absolute",
    top: S.sm,
    left: S.sm,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(44,128,255,0.85)",
    borderRadius: S.radiusBadge,
    paddingHorizontal: 7,
    paddingVertical: 3,
    zIndex: 1,
  },
  timerUrgent: {
    backgroundColor: C.live,
  },
  timerEnded: {
    backgroundColor: C.muted,
  },
  timerText: {
    ...T.badge,
    color: C.textHero,
  },
  bottomLeftBadgeRow: {
    position: "absolute",
    bottom: S.sm,
    left: S.sm,
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
    maxWidth: "88%",
    zIndex: 2,
  },
  watchingTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(44,128,255,0.95)",
    borderRadius: S.radiusBadge,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.28)",
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  watchingTagText: {
    color: C.textHero,
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  hotBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: "rgba(234,61,94,0.9)",
    borderRadius: S.radiusBadge,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  hotText: {
    color: C.textHero,
    fontSize: 8,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  snipeBadge: {
    position: "absolute",
    bottom: S.sm,
    right: S.sm,
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    backgroundColor: "rgba(245,158,11,0.85)",
    borderRadius: S.radiusBadge,
    paddingHorizontal: 5,
    paddingVertical: 2,
    zIndex: 1,
  },
  snipeText: {
    color: C.textHero,
    fontSize: 7,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  gradeBadge: {
    position: "absolute",
    top: S.sm,
    right: S.sm,
    backgroundColor: C.accentGlow,
    borderRadius: S.radiusBadge,
    borderWidth: 1,
    borderColor: C.borderStream,
    paddingHorizontal: 6,
    paddingVertical: 2,
    zIndex: 1,
  },
  gradeBadgeText: {
    ...T.badge,
    color: C.textAccent,
  },

  cardInfo: {
    gap: S.xs,
  },
  cardName: {
    ...T.cardNameSmall,
    fontSize: 13,
  },
  cardEdition: T.edition,
  cardSubMeta: {
    color: C.textSecondary,
    fontSize: 11,
    fontWeight: "700",
  },
  bidRow: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    marginTop: S.sm,
  },
  currentBid: {
    ...T.priceSmall,
    fontSize: 16,
  },
  bidCount: {
    color: C.textSecondary,
    fontSize: 10,
    fontWeight: "600",
  },
  placeBidBtn: {
    backgroundColor: C.accent,
    borderRadius: S.radiusSmall,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    marginTop: S.md,
  },
  placeBidText: {
    color: C.textHero,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.5,
  },

  statsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: S.xs,
  },
  statItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  statText: {
    color: C.textSecondary,
    fontSize: 10,
    fontWeight: "600",
  },

  sellerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: S.sm,
  },
  sellerAvatar: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: C.muted,
    borderWidth: 1,
    borderColor: C.borderAvatar,
    overflow: "hidden",
  },
  sellerName: {
    color: C.textSecondary,
    fontSize: 10,
    fontWeight: "600",
  },

  fab: {
    position: "absolute",
    bottom: S.fabBottom,
    right: S.fabRight,
    width: S.fabSize,
    height: S.fabSize,
    borderRadius: S.fabRadius,
    backgroundColor: C.accent,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: C.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.45,
    shadowRadius: 12,
    elevation: 8,
    zIndex: 10,
  },
});

export const AUCTION_CARD_W = CARD_W;
