import { StyleSheet } from "react-native";
import { C, S } from "../theme";

export const feed = StyleSheet.create({
  safe: { flex: 1, backgroundColor: C.bg },
  root: { flex: 1 },

  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: S.screenPadding,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: C.border,
  },
  headerTitle: { color: C.textBrand, fontSize: 20, fontWeight: "900", letterSpacing: 0.5 },
  headerLeft: { flexDirection: "row", alignItems: "center", gap: 11 },
  headerAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: C.muted,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.border,
  },
  headerAvatarImg: { width: 34, height: 34 },
  headerBtn: {
    width: S.arrowBtnSize,
    height: S.arrowBtnSize,
    borderRadius: S.arrowBtnSize / 2,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.iconBg,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.borderIcon,
  },

  // ── For You / Following tabs ──
  tabsBar: {
    flexDirection: "row",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: C.border,
  },
  tabItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 13,
  },
  tabText: { color: C.textMuted, fontSize: 14.5, fontWeight: "700" },
  tabTextActive: { color: C.textPrimary, fontWeight: "800" },
  tabUnderline: {
    position: "absolute",
    bottom: -StyleSheet.hairlineWidth,
    height: 3,
    width: 46,
    borderRadius: 2,
    backgroundColor: C.accent,
  },

  listContent: { paddingBottom: S.scrollPaddingBottom, flexGrow: 1 },

  // ── Post card ──
  card: {
    paddingHorizontal: S.screenPadding,
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: C.border,
    flexDirection: "row",
    gap: 12,
    backgroundColor: C.bg,
  },
  cardPressed: { backgroundColor: C.surface },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: C.muted,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.borderAvatar,
  },
  avatarImg: { width: 44, height: 44 },
  avatarAnon: { backgroundColor: C.cardAlt },

  cardBody: { flex: 1, gap: 5 },
  authorRow: { flexDirection: "row", alignItems: "center", gap: 5 },
  authorTap: { flexDirection: "row", alignItems: "center", gap: 5, flexShrink: 1 },
  authorName: { color: C.textPrimary, fontWeight: "800", fontSize: 14.5 },
  authorHandle: { color: C.textMuted, fontSize: 13 },
  dot: { color: C.textMuted, fontSize: 13 },
  timeText: { color: C.textMuted, fontSize: 13 },
  anonBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: C.cardAlt,
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: S.radiusPill,
  },
  anonBadgeText: { color: C.textSecondary, fontSize: 11, fontWeight: "700" },

  bodyText: { color: C.textPrimary, fontSize: 15, lineHeight: 21.5 },

  mediaGrid: { flexDirection: "row", flexWrap: "wrap", gap: 4, marginTop: 8 },
  mediaSingle: { width: "100%", height: 248, borderRadius: S.radiusCardInner, backgroundColor: C.muted },
  mediaHalf: { width: "49.4%", height: 150, borderRadius: S.radiusCardInner, backgroundColor: C.muted },
  mediaThird: { width: "32.6%", height: 110, borderRadius: S.radiusCardInner, backgroundColor: C.muted },

  actionsRow: { flexDirection: "row", alignItems: "center", marginTop: 12, marginLeft: -8 },
  action: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderRadius: S.radiusPill,
  },
  actionLiked: { backgroundColor: "rgba(234,61,94,0.12)" },
  actionSpacer: { width: 14 },
  actionText: { color: C.textMuted, fontSize: 13, fontWeight: "600", minWidth: 8 },
  actionTextActive: { color: C.live },
  moreBtn: { marginLeft: "auto", paddingVertical: 4, paddingHorizontal: 6 },

  // ── Composer / FAB ──
  fab: {
    position: "absolute",
    right: S.fabRight,
    bottom: S.fabBottom,
    width: S.fabSize,
    height: S.fabSize,
    borderRadius: S.fabRadius,
    backgroundColor: C.accent,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: C.accent,
    shadowOpacity: 0.4,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },

  // ── Empty / states ──
  centerState: { flex: 1, alignItems: "center", justifyContent: "center", padding: 40, gap: 10, minHeight: 320 },
  emptyIconWrap: {
    width: 72, height: 72, borderRadius: 36,
    alignItems: "center", justifyContent: "center",
    backgroundColor: C.cardAlt, marginBottom: 4,
  },
  emptyTitle: { color: C.textPrimary, fontSize: 17, fontWeight: "800" },
  emptySub: { color: C.textMuted, fontSize: 13, textAlign: "center", lineHeight: 19, maxWidth: 260 },
  emptyBtn: {
    flexDirection: "row", alignItems: "center", gap: 8,
    backgroundColor: C.accent, paddingHorizontal: 20, paddingVertical: 11,
    borderRadius: S.radiusPill, marginTop: 8,
  },
  emptyBtnText: { color: C.textHero, fontSize: 14, fontWeight: "800" },

  // ── End of feed ──
  endFooter: { alignItems: "center", paddingVertical: 28, gap: 6 },
  endFooterText: { color: C.textMuted, fontSize: 12, fontWeight: "700", letterSpacing: 0.3 },

  // ── Skeleton ──
  skeletonCard: {
    paddingHorizontal: S.screenPadding,
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: C.border,
    flexDirection: "row",
    gap: 12,
  },
  skeletonBody: { flex: 1, gap: 8, paddingTop: 2 },

  // ── Composer screen ──
  composerInput: {
    color: C.textPrimary,
    fontSize: 17,
    lineHeight: 24,
    paddingHorizontal: S.screenPadding,
    paddingTop: 12,
    minHeight: 140,
    textAlignVertical: "top",
  },
  composerToolbar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    paddingHorizontal: S.screenPadding,
    paddingVertical: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: C.border,
  },
  toolbarBtn: { flexDirection: "row", alignItems: "center", gap: 6 },
  toolbarBtnText: { color: C.textAccent, fontSize: 13, fontWeight: "700" },
  composerCounter: {
    color: C.textMuted,
    fontSize: 12,
    fontWeight: "600",
    fontVariant: ["tabular-nums"],
  },
  composerCounterOver: { color: C.danger },
  commentCounter: {
    color: C.textMuted,
    fontSize: 12,
    fontWeight: "600",
    textAlign: "right",
    paddingHorizontal: S.screenPadding,
    paddingBottom: 4,
    fontVariant: ["tabular-nums"],
  },
  anonToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginLeft: "auto",
  },
  anonToggleLabel: { color: C.textSecondary, fontSize: 13, fontWeight: "700" },

  postBtn: {
    backgroundColor: C.accent,
    paddingHorizontal: 18,
    paddingVertical: 9,
    borderRadius: S.radiusPill,
  },
  postBtnDisabled: { backgroundColor: C.muted },
  postBtnText: { color: C.textHero, fontWeight: "800", fontSize: 14 },
  postBtnTextDisabled: { color: C.textMuted },

  thumbRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, paddingHorizontal: S.screenPadding, marginTop: 8 },
  thumb: { width: 84, height: 84, borderRadius: S.radiusSmall, backgroundColor: C.muted },
  thumbRemove: {
    position: "absolute",
    top: -6,
    right: -6,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: C.danger,
    alignItems: "center",
    justifyContent: "center",
  },

  // ── Comments ──
  commentRow: {
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: S.screenPadding,
    paddingVertical: 12,
  },
  // Separator between top-level comment threads (not between every row).
  commentThreadTop: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: C.border,
  },
  commentAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: C.muted,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  commentAvatarSmall: { width: 28, height: 28, borderRadius: 14 },
  commentBody: { flex: 1, gap: 3 },
  commentText: { color: C.textPrimary, fontSize: 14, lineHeight: 20 },

  commentBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: S.screenPadding,
    paddingVertical: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: C.border,
  },
  commentInput: {
    flex: 1,
    color: C.textPrimary,
    fontSize: 15,
    backgroundColor: C.cardInner,
    borderRadius: S.radiusPill,
    paddingHorizontal: 16,
    paddingVertical: 9,
    maxHeight: 100,
  },
  commentSend: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: C.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  commentSendDisabled: { backgroundColor: C.muted },

  // ── Threaded replies ──
  commentReplyIndent: {
    marginLeft: 32,
    borderLeftWidth: 2,
    borderLeftColor: C.border,
    paddingLeft: 12,
    paddingVertical: 9,
  },
  replyParentLabel: { color: C.textMuted, fontSize: 11, marginBottom: 1 },
  commentActionsRow: { flexDirection: "row", alignItems: "center", gap: 16, marginTop: 4 },
  replyBtnText: { color: C.textSecondary, fontSize: 12, fontWeight: "700" },
  commentLikeCol: {
    alignItems: "center",
    justifyContent: "flex-start",
    paddingTop: 1,
    minWidth: 26,
    gap: 2,
  },
  commentLikeCount: {
    color: C.textMuted,
    fontSize: 11,
    fontWeight: "700",
    fontVariant: ["tabular-nums"],
  },
  commentLikeCountActive: { color: C.live },
  repliesToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginLeft: 32,
    borderLeftWidth: 2,
    borderLeftColor: C.border,
    paddingLeft: 12,
    paddingRight: S.screenPadding,
    paddingVertical: 8,
  },
  repliesToggleText: { color: C.textSecondary, fontSize: 12.5, fontWeight: "700" },
  replyingChip: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    paddingHorizontal: S.screenPadding,
    paddingVertical: 8,
    backgroundColor: C.cardInner,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: C.border,
  },
  replyingChipText: { color: C.textSecondary, fontSize: 12, flex: 1 },
});
