import { StyleSheet } from "react-native";
import { C, S } from "../theme";

export const vendorHub = StyleSheet.create({
  safe: { flex: 1, backgroundColor: C.bg },
  loadingWrap: { flex: 1, alignItems: "center", justifyContent: "center" },

  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: S.screenPadding,
    paddingVertical: 12,
    gap: S.md,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: C.elevated,
    borderWidth: 1,
    borderColor: C.borderIcon,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    flex: 1,
    color: C.textPrimary,
    fontSize: 18,
    fontWeight: "800",
    textAlign: "center",
  },

  // ── Tabs ──
  tabRow: {
    flexDirection: "row",
    marginHorizontal: S.screenPadding,
    backgroundColor: C.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    padding: 3,
    marginBottom: S.lg,
  },
  tabBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 9,
    borderRadius: 10,
    gap: 5,
  },
  tabBtnActive: {
    backgroundColor: C.accentGlow,
  },
  tabLabel: {
    color: C.textMuted,
    fontSize: 11,
    fontWeight: "700",
  },
  tabLabelActive: {
    color: C.accent,
  },

  content: {
    paddingHorizontal: S.screenPadding,
    paddingBottom: 60,
  },

  // ── Overview ──
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 20,
  },
  statCard: {
    width: "48%" as any,
    backgroundColor: C.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    padding: 14,
    gap: 6,
  },
  statIconRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  statIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  statValue: {
    color: C.textPrimary,
    fontSize: 22,
    fontWeight: "900",
  },
  statLabel: {
    color: C.textSecondary,
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.3,
  },
  quickActions: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 20,
  },
  quickBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: C.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
    paddingVertical: 14,
  },
  quickBtnPrimary: {
    backgroundColor: C.accent,
    borderColor: C.accent,
  },
  quickBtnText: {
    color: C.textPrimary,
    fontSize: 13,
    fontWeight: "700",
  },
  quickBtnTextPrimary: {
    color: "#fff",
  },
  recentOrdersSection: {
    marginBottom: 20,
  },
  recentOrderCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: C.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
    padding: 12,
    gap: 10,
    marginBottom: 8,
  },
  recentOrderThumb: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: C.elevated,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  recentOrderThumbImg: {
    width: 40,
    height: 40,
    borderRadius: 10,
  },
  recentOrderInfo: {
    flex: 1,
  },
  recentOrderName: {
    color: C.textPrimary,
    fontSize: 13,
    fontWeight: "700",
  },
  recentOrderMeta: {
    color: C.textSecondary,
    fontSize: 11,
    fontWeight: "500",
    marginTop: 2,
  },
  recentOrderRight: {
    alignItems: "flex-end",
    gap: 4,
  },
  recentOrderPrice: {
    color: C.accent,
    fontSize: 13,
    fontWeight: "800",
  },

  // ── Orders ──
  filterRow: {
    flexDirection: "row",
    paddingHorizontal: S.screenPadding,
    gap: 8,
    marginBottom: S.md,
  },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
  },
  filterChipActive: {
    backgroundColor: C.accentGlow,
    borderColor: C.accent,
  },
  filterChipText: {
    color: C.textMuted,
    fontSize: 12,
    fontWeight: "700",
  },
  filterChipTextActive: {
    color: C.accent,
  },
  orderCard: {
    backgroundColor: C.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    marginBottom: 10,
    overflow: "hidden",
  },
  orderCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 6,
  },
  orderIdText: {
    color: C.textMuted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  orderDateText: {
    color: C.textMuted,
    fontSize: 10,
    fontWeight: "600",
  },
  orderCardBody: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingBottom: 10,
    gap: 10,
  },
  orderItemThumb: {
    width: 48,
    height: 48,
    borderRadius: 10,
    backgroundColor: C.elevated,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  orderItemThumbImg: {
    width: 48,
    height: 48,
    borderRadius: 10,
  },
  orderItemInfo: {
    flex: 1,
  },
  orderItemName: {
    color: C.textPrimary,
    fontSize: 13,
    fontWeight: "700",
  },
  orderItemMeta: {
    color: C.textSecondary,
    fontSize: 11,
    fontWeight: "500",
    marginTop: 1,
  },
  orderBuyerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 3,
  },
  orderBuyerDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: C.accent,
  },
  orderBuyerName: {
    color: C.textAccent,
    fontSize: 11,
    fontWeight: "600",
  },
  orderItemRight: {
    alignItems: "flex-end",
    gap: 4,
  },
  orderItemPrice: {
    color: C.accent,
    fontSize: 14,
    fontWeight: "900",
  },
  orderItemQty: {
    color: C.textSecondary,
    fontSize: 11,
    fontWeight: "600",
  },
  orderCardFooter: {
    flexDirection: "row",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: C.border,
    padding: 10,
    gap: 8,
  },
  fulfillmentChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    borderWidth: 1,
  },
  fulfillmentChipText: {
    fontSize: 11,
    fontWeight: "700",
  },
  fulfillmentBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderRadius: 10,
    paddingVertical: 10,
  },
  fulfillmentBtnText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "800",
  },

  // ── Store Design ──
  previewCard: {
    borderRadius: S.radiusCard,
    borderWidth: 1,
    backgroundColor: C.surface,
    overflow: "hidden",
    marginBottom: S.xl,
  },
  previewBanner: {
    height: 100,
    width: "100%",
  },
  previewBody: {
    padding: S.lg,
  },
  previewLogoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: S.md,
    marginTop: -36,
  },
  previewLogo: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.bg,
  },
  previewInfo: { flex: 1, paddingTop: 14 },
  previewName: {
    color: C.textPrimary,
    fontSize: 16,
    fontWeight: "800",
  },
  previewDesc: {
    color: C.textSecondary,
    fontSize: 12,
    fontWeight: "500",
    marginTop: 2,
  },

  // Form
  sectionTitle: {
    color: C.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginBottom: S.sm,
    marginLeft: 4,
  },
  formCard: {
    backgroundColor: C.surface,
    borderRadius: S.radiusCard,
    borderWidth: 1,
    borderColor: C.border,
    padding: S.lg,
    gap: S.lg,
    marginBottom: S.xl,
  },
  field: { gap: 6 },
  label: {
    color: C.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  input: {
    backgroundColor: C.elevated,
    borderRadius: S.radiusSmall,
    borderWidth: 1,
    borderColor: C.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: C.textPrimary,
    fontSize: 14,
    fontWeight: "500",
  },
  inputMulti: {
    minHeight: 72,
    textAlignVertical: "top",
  },
  uploadBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: C.elevated,
    borderRadius: S.radiusSmall,
    borderWidth: 1,
    borderColor: C.border,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  uploadBtnText: {
    color: C.textPrimary,
    fontSize: 13,
    fontWeight: "600",
  },
  colorRow: {
    flexDirection: "row",
    gap: 12,
    flexWrap: "wrap",
    marginBottom: S.xl,
  },
  colorDot: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  colorDotActive: {
    borderWidth: 3,
    borderColor: "#fff",
  },
  saveBtn: {
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
  },
  saveBtnText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "800",
  },

  // Display Items (inside Store tab)
  displayHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 2,
  },
  displayCount: {
    color: C.accent,
    fontSize: 13,
    fontWeight: "800",
  },
  displayHint: {
    color: C.textSecondary,
    fontSize: 12,
    fontWeight: "500",
    marginBottom: S.lg,
  },
  displayRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: C.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    padding: 12,
    gap: 10,
    marginBottom: 8,
  },
  displayOrder: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: C.accentGlow,
    alignItems: "center",
    justifyContent: "center",
  },
  displayOrderText: {
    color: C.accent,
    fontSize: 12,
    fontWeight: "900",
  },
  displayInfo: { flex: 1 },
  displayName: {
    color: C.textPrimary,
    fontSize: 13,
    fontWeight: "700",
  },
  displayMeta: {
    color: C.textSecondary,
    fontSize: 11,
    fontWeight: "500",
    marginTop: 2,
  },
  displayPrice: {
    color: C.accent,
    fontSize: 12,
    fontWeight: "800",
    marginTop: 3,
  },
  displayActions: {
    flexDirection: "row",
    gap: 8,
  },
  miniBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: C.elevated,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: "center",
    justifyContent: "center",
  },
  miniBtnDisabled: {
    opacity: 0.35,
  },

  // ── Empty states ──
  emptyCard: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.surface,
    borderRadius: S.radiusCard,
    borderWidth: 1,
    borderColor: C.border,
    paddingVertical: 40,
    gap: 8,
  },
  emptyTitle: {
    color: C.textPrimary,
    fontSize: 15,
    fontWeight: "800",
  },
  emptySub: {
    color: C.textSecondary,
    fontSize: 12,
    fontWeight: "500",
    textAlign: "center",
    paddingHorizontal: 40,
  },

  // ── My Listings ──
  listingsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: S.screenPadding,
    marginBottom: S.md,
  },
  newListingBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: C.accent,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 6,
  },
  newListingBtnText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "800",
  },
  listingCardWrap: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.surface,
    marginBottom: 8,
    overflow: "hidden",
  },
  listingRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    padding: 12,
    gap: 10,
  },
  listingThumb: {
    width: 48,
    height: 48,
    borderRadius: 10,
    backgroundColor: C.elevated,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  listingThumbImg: {
    width: 48,
    height: 48,
    borderRadius: 10,
  },
  listingInfo: { flex: 1 },
  listingName: {
    color: C.textPrimary,
    fontSize: 13,
    fontWeight: "700",
  },
  listingMeta: {
    color: C.textSecondary,
    fontSize: 11,
    fontWeight: "500",
    marginTop: 2,
  },
  listingPrice: {
    color: C.accent,
    fontSize: 13,
    fontWeight: "800",
    marginTop: 2,
  },
  listingQty: {
    color: C.textSecondary,
    fontSize: 11,
    fontWeight: "600",
  },
  listingActions: {
    alignItems: "flex-end",
    gap: 8,
  },
  rowActionButtons: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  listingActionBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.border,
    paddingHorizontal: 10,
    minHeight: 34,
    backgroundColor: C.elevated,
  },
  listingActionBtnText: {
    color: C.textPrimary,
    fontSize: 11,
    fontWeight: "700",
  },
  listingActionBtnDangerText: {
    color: C.danger,
  },
  statusChip: {
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  statusActive: {
    backgroundColor: "rgba(34,197,94,0.12)",
  },
  statusInactive: {
    backgroundColor: "rgba(100,116,139,0.12)",
  },
  statusText: {
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  statusTextActive: {
    color: C.success,
  },
  statusTextInactive: {
    color: C.textMuted,
  },
  displayToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.border,
    paddingHorizontal: 10,
    minHeight: 34,
  },
  displayToggleActive: {
    borderColor: "rgba(245,158,11,0.4)",
    backgroundColor: "rgba(245,158,11,0.08)",
  },
  displayToggleText: {
    color: C.textMuted,
    fontSize: 11,
    fontWeight: "700",
  },
  displayToggleTextActive: {
    color: "#F59E0B",
  },
  listingEditor: {
    borderTopWidth: 1,
    borderTopColor: C.border,
    backgroundColor: C.elevated,
    padding: 10,
    gap: 8,
  },
  editorRow: {
    flexDirection: "row",
    gap: 8,
  },
  editorInput: {
    backgroundColor: C.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.border,
    paddingHorizontal: 10,
    paddingVertical: 9,
    color: C.textPrimary,
    fontSize: 13,
    fontWeight: "500",
  },
  editorHalf: {
    flex: 1,
  },
  editorActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
    marginTop: 2,
  },
  editorCancelBtn: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.surface,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  editorCancelText: {
    color: C.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  editorSaveBtn: {
    borderRadius: 8,
    backgroundColor: C.accent,
    paddingHorizontal: 12,
    paddingVertical: 8,
    minWidth: 108,
    alignItems: "center",
    justifyContent: "center",
  },
  editorSaveText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "800",
  },

  // ── Toast ──
  toast: {
    position: "absolute",
    bottom: 40,
    left: 20,
    right: 20,
    backgroundColor: C.success,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  toastText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "700",
  },
});
